# workflow to release assets as part of the release
name: Upload Release Asset
on:
  push:
    tags:
      - "v*"

permissions:
  packages: write
  contents: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set release
        run: echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true

      - name: Build
        run: make

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: bin/*
          draft: true
          prerelease: false